"""empty message

Revision ID: b402e71eee19
Revises: 9fbe0f0d5e2a
Create Date: 2025-11-28 19:57:33.026310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b402e71eee19'
down_revision = '9fbe0f0d5e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t')
    op.drop_table('test')
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('normal_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('trivialer_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('trivialer_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('normal_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    op.create_table('t',
    sa.Column('x', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
